name: Build and deploy package to npm

on:
  push:
    branches:
      - master
      - qa

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build application

    steps:
      # Default git setup
      - uses: actions/checkout@v2

      - run: npm install
      - run: npm run build

      - uses: actions/upload-artifact@v1
        with:
          name: repo
          path: .

  npm-publish:
    runs-on: ubuntu-latest
    name: Publish to public artifactory
    needs: build
    steps:
      - name: Download Cache
        uses: actions/download-artifact@v1
        with:
          name: repo

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

          # Create .npmrc file with token from secret
      - uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - run: npm publish

  intility-publish:
    runs-on: ubuntu-latest
    name: Publish to private artifactory
    needs: build
    steps:
      - name: Download Cache
        uses: actions/download-artifact@v1
        with:
          name: repo

      - run: ls
