name: Build and deploy package to npm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          echo $PUBLIC_NPM_TOKEN
        env:
          PUBLIC_NPM_TOKEN: ${{secrets.PUBLIC_NPM_TOKEN}}
      - run: npm install
      - run: npm run build
      
      - run: |
          echo //registry.npmjs.org/:_authToken=$PUBLIC_NPM_TOKEN >> .npmrc
        env:
          PUBLIC_NPM_TOKEN: ${{secrets.PUBLIC_NPM_TOKEN}}
      - run: npm publish --access public
      - run: rm .npmrc
