name: Build and deploy package to npm

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm run build

  npm-publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Default git setup
      - uses: actions/checkout@v2

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

          # Create .npmrc file with token from secret
      - uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      # publish to npm public registry
      - run: npm publish

  intility-publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo Hello World
