name: Build and deploy package to npm

on:
  push:
    branches:
      - master
      - qa

defaults:
  run:
    shell: bash

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      # Default git setup
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        name: Setup public artifactory
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      # Install, build and publish
      - run: npm install
      - run: npm run build
      - run: npm publish
        name: Publish to public artifactory
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
